feat: add single link payments
espresso-cash/espresso-cash-public pull request #1071
Opened 2023-09-25 02:39 UTC by justinenerio

## Changes

- removed firebase dynamic link dependencies
- added outgoing and incoming single link modules

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [ ] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2023-10-03 20:08 UTC, ookami-kb commented
@justinenerio please resolve conflicts

2023-10-04 04:08 UTC, justinenerio commented
@ookami-kb have resolved conflicts and issues

2023-10-04 19:44 UTC, ookami-kb requested changes
Also, deep link settings for Android/iOS should be changed – the app should only support new links format.

2023-10-04 19:44 UTC, ookami-kb commented on packages/espressocash_app/lib/data/db/db.dart
> +            await m.createTable(oLPRows);
It should be a separate DB version, 39.

2023-10-04 19:44 UTC, ookami-kb commented on packages/espressocash_app/lib/features/outgoing_split_key_payments/screens/oskp_confirmation_screen.dart
>          children: [
Ok, since we change these modules anyway, and they will not work properly, let's remove them within this PR.

2023-10-04 19:44 UTC, ookami-kb commented on packages/espressocash_app/lib/landing/main.dart
> +  setUrlStrategy(PathUrlStrategy());
Shouldn't be changed in this PR.

2023-10-05 03:16 UTC, justinenerio commented
@ookami-kb have updated the pr

2023-10-05 19:33 UTC, ookami-kb requested changes

2023-10-05 19:33 UTC, ookami-kb commented on packages/espressocash_app/lib/features/outgoing_split_key_payments/services/tx_confirmed_watcher.dart
Incoming split key payments can be removed as well.

2023-10-08 22:42 UTC, ookami-kb approved these changes

2023-10-08 22:42 UTC, merged