feat: add incoming dln payments
espresso-cash/espresso-cash-public pull request #1300
Opened 2024-03-08 15:50 UTC by justinenerio

## Changes

- adds incoming dln payments
- update landing web pages theme

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2024-03-31 21:12 UTC, ookami-kb requested changes

2024-03-31 21:12 UTC, ookami-kb commented on packages/espressocash_landing/lib/l10n/device_locale.dart
Why is it not in common package?

2024-03-31 21:12 UTC, ookami-kb commented on packages/espressocash_landing/lib/utils/format_amount.dart
Why is it not in common?

2024-03-31 21:12 UTC, ookami-kb commented on packages/espressocash_landing/lib/features/payment_request/widgets/dropdown.dart
> +// ignore_for_file: avoid-non-null-assertion
Don't ignore.

2024-03-31 21:12 UTC, ookami-kb commented on packages/espressocash_landing/lib/features/web3/web3_service.dart
> +// ignore_for_file: avoid-unnecessary-type-casts, unnecessary_cast, avoid_web_libraries_in_flutter
Don't ignore (except for `avoid_web_libraries_in_flutter`).

2024-04-01 04:19 UTC, justinenerio commented on packages/espressocash_landing/lib/l10n/device_locale.dart
resolved in pr: https://github.com/espresso-cash/espresso-cash-public/pull/1358

2024-04-24 15:47 UTC, closed without merging