feat: token details page
espresso-cash/espresso-cash-public pull request #1501
Opened 2024-06-17 15:58 UTC by Jaxiii

## Changes

Display token details upon click

## Related issues

Fixes #1496 

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2024-06-19 19:19 UTC, Jaxiii commented
https://github.com/espresso-cash/espresso-cash-public/assets/17258221/f68b647f-86d0-4edd-a050-fed340f908c7

2024-07-15 14:40 UTC, ookami-kb requested changes

2024-07-15 14:40 UTC, ookami-kb commented on packages/solana/lib/src/rpc/dto/return_data.dart
Please extract changes to `solana` package into a separate PR.

2024-07-15 14:40 UTC, ookami-kb commented on packages/solana/lib/src/rpc/dto/return_data.dart
> +  final List<dynamic> data;
Why is it `List<dynamic>`?

2025-01-06 22:07 UTC, ookami-kb commented on packages/espressocash_app/lib/features/currency/models/amount.dart
> +  String formatRate(double rate, Locale locale) {
Please add some unit tests for this method.

2025-01-08 19:39 UTC, Merculiar commented
https://github.com/espresso-cash/espresso-cash-public/pull/1664
Should be merged first

2025-01-12 20:55 UTC, ookami-kb requested changes

2025-01-12 20:55 UTC, ookami-kb commented on packages/espressocash_app/lib/features/token_details/widgets/token_app_bar.dart
> +// ignore_for_file: avoid-single-child-column-or-row
Why is it needed? Can you do it without row?

2025-01-12 20:55 UTC, ookami-kb commented on packages/espressocash_app/lib/features/activities/widgets/recent_token_activity.dart
> +                  late final IList<TxCommon> sortedTxs;
This looks error-prone. What if transactions == null? It will never be initialized.

Also, the whole mapping in widget looks too complex, let's extract it to logic layer – no bloc is needed but something lightweight like ChangeNotifier would make sense for preparing the data.

2025-01-12 20:55 UTC, ookami-kb commented on packages/espressocash_app/lib/features/activities/services/tx_updater.dart
> +  void init() {
Why not just mark `call` as `@PostConstruct`?

2025-01-12 21:40 UTC, Merculiar commented on packages/espressocash_app/lib/features/token_details/widgets/token_app_bar.dart
> +// ignore_for_file: avoid-single-child-column-or-row
Changed

2025-01-12 21:41 UTC, Merculiar commented on packages/espressocash_app/lib/features/activities/services/tx_updater.dart
> +  void init() {
Updated

2025-01-12 23:01 UTC, Merculiar commented
Solana beta workflow has 1 test failing, version 2.1.8 was just release without changelog currently. [https://github.com/anza-xyz/agave/releases](url)

2025-01-14 20:32 UTC, ookami-kb approved these changes

2025-01-14 20:32 UTC, merged