feat: ambassador module
espresso-cash/espresso-cash-public pull request #1612
Opened 2024-11-20 12:30 UTC by justinenerio

## Changes

- adds generation of ambassador qr code
- can scan ambassador qr code and save to backend
- enabled by feature flag

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [ ] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2024-11-24 07:20 UTC, justinenerio commented
can be merged after: https://github.com/espresso-cash/espresso-cash-public/pull/1616

2024-11-25 20:49 UTC, ookami-kb requested changes

2024-11-26 07:28 UTC, justinenerio commented on packages/espressocash_app/lib/features/ambassador/services/ambassador_service.dart
> +  Future<void> init() async {
Updated cache and flow

2024-11-26 20:08 UTC, ookami-kb approved these changes

2024-11-26 20:08 UTC, merged