feat: brij error handling
espresso-cash/espresso-cash-public pull request #1651
Opened 2024-12-20 06:06 UTC by justinenerio

## Changes

- updates error handling for email and phone verification
- send unknown errors to sentry

## Related issues

Related to #1627

## Checklist

- [x] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2024-12-20 19:43 UTC, ookami-kb requested changes

2024-12-20 19:43 UTC, ookami-kb commented on packages/espressocash_app/lib/features/kyc_sharing/widgets/extensions.dart
> +// ignore_for_file: avoid-wildcard-cases-with-enums
Don't suppress it, list all cases instead.

2024-12-20 19:43 UTC, ookami-kb commented on packages/espressocash_app/lib/features/kyc_sharing/screens/phone_confirmation_screen.dart
> +// ignore_for_file: avoid-wildcard-cases-with-enums
Same here.

2024-12-20 19:43 UTC, ookami-kb commented on packages/espressocash_app/lib/features/kyc_sharing/utils/kyc_exception.dart
> +        final s when s.contains('60203') =>
That's not maintainable, let's think about proper error responding on backend side.

2025-01-08 14:32 UTC, justinenerio commented on packages/espressocash_app/lib/features/kyc_sharing/utils/kyc_exception.dart
> +        final s when s.contains('60203') =>
updated, parsing of errors are done in backend instead. can be merged after https://github.com/espresso-cash/brij-verifier/pull/21

2025-01-13 22:06 UTC, ookami-kb approved these changes

2025-01-13 22:06 UTC, merged