feat: new investment screen
espresso-cash/espresso-cash-public pull request #781
Opened 2023-02-07 23:35 UTC by rhbrunetto

## Changes

- Adds new layout for investment screen

## Related issues

Fixes #779 

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2023-02-11 17:47 UTC, ookami-kb commented
@rhbrunetto please fix conflicts.

2023-02-11 17:53 UTC, ookami-kb requested changes

2023-02-11 17:53 UTC, ookami-kb commented on packages/espressocash_app/pubspec.lock
> +  dart: ">=2.19.0 <4.0.0"
Not needed.

2023-02-11 17:53 UTC, ookami-kb commented on packages/espressocash_app/lib/app/screens/authenticated/investments/components/investment_header.dart
> +        height: 280,
I don't like this hard-coded height. Can we do it in a different way?

2023-02-11 17:53 UTC, ookami-kb commented on packages/espressocash_app/lib/l10n/app_en.arb
> +  "startedInvestingTitle": "Started Investing",
Shouldn't it be `Start Investing`?

2023-02-11 17:55 UTC, antoineherzog commented on packages/espressocash_app/lib/l10n/app_en.arb
> +  "startedInvestingTitle": "Started Investing",
Yes I think so!

2023-02-14 21:29 UTC, ookami-kb requested changes

2023-02-14 21:29 UTC, ookami-kb commented on packages/espressocash_app/pubspec.lock
> +  dart: ">=2.19.0 <4.0.0"
Not resolved.

2023-02-15 18:07 UTC, ookami-kb approved these changes

2023-02-15 18:07 UTC, merged