ci: update solana and flutter actions
espresso-cash/espresso-cash-public pull request #907
Opened 2023-03-28 13:20 UTC by justinenerio

## Changes

## Related issues

Fixes #___

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [ ] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2023-03-28 22:08 UTC, ookami-kb requested changes

2023-03-28 22:08 UTC, ookami-kb commented on .github/workflows/check_pr.yml
> +      - run: flutter --version
Not needed.

2023-03-28 22:08 UTC, ookami-kb commented on .github/workflows/check_pr.yml
> +          channel: 'stable'
Let's use specific version everywhere for reproducible builds.

2023-03-29 15:38 UTC, ookami-kb commented on .github/workflows/check_pr.yml
> +  FLUTTER_VERSION: ${{ github.event.inputs.version }}
It's not provided anywhere.

2023-03-30 07:39 UTC, justinenerio commented on .github/workflows/check_pr.yml
> +  FLUTTER_VERSION: ${{ github.event.inputs.version }}
Updated to hardcoded version

2023-04-01 18:13 UTC, ookami-kb approved these changes

2023-04-01 18:13 UTC, merged